# Site settings
title: Kel's Blog
name: Kel Cecil
email: kelcecil@praisechaos.com
description: > # this means to ignore newlines until "baseurl:"
  Ramblings of a polygot developer that loves
  to build things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kelcecil.com" # the base hostname & protocol for your site
twitter_username: praisechaos
github_username:  kelcecil

# Build settings
markdown: kramdown
